<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SayHello.ShortLink</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.BackgroundWorkers" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Caching" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Mapperly" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.6.0" />
    <ProjectReference Include="..\SayHello.ShortLink.Common.Application.Contracts\SayHello.ShortLink.Common.Application.Contracts.csproj" />
    <ProjectReference Include="..\SayHello.ShortLink.Domain\SayHello.ShortLink.Domain.csproj" />
  </ItemGroup>
</Project>
