<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <ItemGroup>
    <ProjectReference Include="..\SayHello.ShortLink.Subscription.Domain.Shared\SayHello.ShortLink.Subscription.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\SayHello.ShortLink\src\SayHello.ShortLink.Domain\SayHello.ShortLink.Domain.csproj" />
    <ProjectReference Include="..\..\..\SayHello.Subscription\src\SayHello.Subscription.Public.Application.Contracts\SayHello.Subscription.Public.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
