<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SayHello.ShortLink.Admin</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Mapperly" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Domain" Version="10.6.0" />
    <ProjectReference Include="..\SayHello.ShortLink.Admin.Application.Contracts\SayHello.ShortLink.Admin.Application.Contracts.csproj" />
    <ProjectReference Include="..\SayHello.ShortLink.Common.Application\SayHello.ShortLink.Common.Application.csproj" />
  </ItemGroup>
</Project>
