<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.DistributedLocking" Version="10.6.0" />
    <ProjectReference Include="..\SayHello.Subscription.Domain.Shared\SayHello.Subscription.Domain.Shared.csproj" />
  </ItemGroup>
</Project>
