<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SayHello.ShortLink</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="10.6.0" />
    <ProjectReference Include="..\SayHello.ShortLink.Domain.Shared\SayHello.ShortLink.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
