<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SayHello.ShortLink.WebHost</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Identity.Domain.Shared" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.BackgroundJobs.Domain.Shared" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.AuditLogging.Domain.Shared" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Domain.Shared" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Domain.Shared" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Domain.Shared" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Domain.Shared" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.OpenIddict.Domain.Shared" Version="10.6.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\WebHost\*.json" />
    <Content Remove="Localization\WebHost\*.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\modules\SayHello.ShortLink\src\SayHello.ShortLink.Domain.Shared\SayHello.ShortLink.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\modules\SayHello.Subscription\src\SayHello.Subscription.Domain.Shared\SayHello.Subscription.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
