<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SayHello.ShortLink.Public</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Http.Client" Version="10.6.0" />
    <ProjectReference Include="..\SayHello.ShortLink.Public.Application.Contracts\SayHello.ShortLink.Public.Application.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*generate-proxy.json" />
    <Content Remove="**\*generate-proxy.json" />
  </ItemGroup>
</Project>
