<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SayHello.ShortLink</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SayHello.ShortLink.Domain\SayHello.ShortLink.Domain.csproj" />
    <ProjectReference Include="..\SayHello.ShortLink.TestBase\SayHello.ShortLink.TestBase.csproj" />
  </ItemGroup>


</Project>
